# Generated by Django 4.2.9 on 2026-03-28 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_recurring_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recurring_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='core.recurringorder'),
        ),
    ]
